### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Ultra78** [llamadevelopment/BanSystem#17]
Hello, I need your help !!! 
When I click on shop nothing apperes, so I dont see anything. And I also have Llama economy installed
![Screenshot_2021-12-05-18-15-48-464_com mojang minecraftpe](https://user-images.githubusercontent.com/89126006/144756505-ddec0704-beb0-49cb-b01a-6dcacde3f00c.jpg)

Thanks

**Comment by Mundschutziii** [comment]
That is no an issue of the BanSystem.
